# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Generators',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/Generators',
                'lib_path': 'Generators'},
  'syms': {'Generators.DiffusersPipeline': {}}}
